### ISSUE TITLE
not able to use the smote method 

### ISSUE THREAD

**Issue by arjunpuri7** [gykovacs/imbalanced_databases#1]
hello dear,
             i am not able to gent result on imbalanced dataset (abalone9-18.csv). Perform following steps :-
import smote_variants as sv
import pandas as pd
from sklearn.model_selection import train_test_split
data=pd.read_csv("..../abalone9-18.csv")
X=data.drop('8',axis=1)
print(X)
y=data.iloc[:,-1]
print(y)
over=sv.SMOTE_ENN()
X_samp, y_samp= over.sample(X,y) 

and getting following error:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2524             try:
-> 2525                 return self._engine.get_loc(key)
   2526             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 41

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-13-ad1152f72f26> in <module>()
     10 print(y)
     11 over=sv.SMOTE_ENN()
---> 12 X_samp, y_samp= over.sample(X,y)
     13 #print(X_samp)

~\Anaconda3\lib\site-packages\smote_variants\_smote_variants.py in sample(self, X, y)
   1490 
   1491         smote= SMOTE(self.proportion, self.n_neighbors, n_jobs= self.n_jobs)
-> 1492         X_new, y_new= smote.sample(X, y)
   1493 
   1494         enn= EditedNearestNeighbors(n_jobs= self.n_jobs)

~\Anaconda3\lib\site-packages\smote_variants\_smote_variants.py in sample(self, X, y)
   1294             base_idx= np.random.randint(len(X_min))
   1295             neighbor_idx= np.random.choice(ind[base_idx][1:])
-> 1296             samples.append(self.sample_between_points(X_min[base_idx], X_min[neighbor_idx]))
   1297 
   1298         return np.vstack([X, np.vstack(samples)]), np.hstack([y, np.hstack([self.minority_label]*num_to_sample)])

~\Anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2137             return self._getitem_multilevel(key)
   2138         else:
-> 2139             return self._getitem_column(key)
   2140 
   2141     def _getitem_column(self, key):

~\Anaconda3\lib\site-packages\pandas\core\frame.py in _getitem_column(self, key)
   2144         # get column
   2145         if self.columns.is_unique:
-> 2146             return self._get_item_cache(key)
   2147 
   2148         # duplicate columns & possible reduce dimensionality

~\Anaconda3\lib\site-packages\pandas\core\generic.py in _get_item_cache(self, item)
   1840         res = cache.get(item)
   1841         if res is None:
-> 1842             values = self._data.get(item)
   1843             res = self._box_item_values(item, values)
   1844             cache[item] = res

~\Anaconda3\lib\site-packages\pandas\core\internals.py in get(self, item, fastpath)
   3841 
   3842             if not isna(item):
-> 3843                 loc = self.items.get_loc(item)
   3844             else:
   3845                 indexer = np.arange(len(self.items))[isna(self.items)]

~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2525                 return self._engine.get_loc(key)
   2526             except KeyError:
-> 2527                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2528 
   2529         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 41

**Comment by gykovacs** [comment]
Hi, thank you for reporting the issue, let me look into it. What version of Python are you using, with which version of pandas, numpy, sklearn? Did you install imbalanced_databases and smote_variants from github or from the PyPi repo? Thanks!

**Comment by arjunpuri7** [comment]
pandas version: 0.22.0
python version: 3.6.4
numpy version 1.15.4
sklearn version 0.19.1
    I don't install imbalanced_databases and download smote_variants from pypi

**Comment by arjunpuri7** [comment]
hello dear,
Is smote_variants work without imbalanced_databases?

**Comment by gykovacs** [comment]
Hi arjunpuri7,

yeah, it should work without imbalanced_datasets, too. It should work on any dataset. I will examine the issue in a couple of hours and come back with some solution. It should definitely work.

**Comment by gykovacs** [comment]
Hi arjunpuri7,

this code here works and prints the output below:
```python
import smote_variants as sv
import pandas as pd
from sklearn.model_selection import train_test_split
import imbalanced_databases as imbd

data= imbd.load_abalone9_18()   
X= data['data']
y= data['target']

over=sv.SMOTE_ENN()
X_samp, y_samp= over.sample(X, y)
print(len(X), len(X_samp))
```

```bash
2019-04-09 19:58:38,920:INFO:SMOTE_ENN: Running sampling via ('SMOTE_ENN', "{'proportion': 1.0, 'n_neighbors': 5, 'n_jobs': 1}")
2019-04-09 19:58:38,920:INFO:SMOTE: Running sampling via ('SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'n_jobs': 1}")
2019-04-09 19:58:38,933:INFO:EditedNearestNeighbors: Running noise removal via EditedNearestNeighbors
731 1291
```

There can be multiple problems with your approach:
* first of all, the proper encoding of features is a requirement, I don't know if all the features read from the csv you have are numerical. If categorical attributes are there, it definitely won't work with smote_variants out of the box.
* the other important thing is that smote_variants works with numpy array, and it was not tested and it is not intended to be used on pandas data frames directly. If all the features in your dataframe are numeric, call the ```sample``` function on X.values rather than directly on ```X```.

Also, the ```imbalanced_databases``` package contains all the commonly used imbalanced databases in a properly encoded format, it might be worth using it to avoid all the struggling with encoding the features.

I hope this helped!

**Comment by arjunpuri7** [comment]
hello dear,
     I have to perform some other analysis to on these datasets and required your techniques to analysis. as you said that this technique will work with pandas too. here i am sending file of required dataset.please see and tell me why it is not working with my dataset. 
   In abalone 9-18 dataset in 8th attribute '0'means negative instances and '1' means positive instances. Please run this dataset with your technique and let me know what wrong with this datasets and I need only

**Comment by arjunpuri7** [comment]
hello dear,
I have to perform some other analysis to on these datasets and required
your techniques to analysis. as you said that this technique will work with
pandas too. here i am sending file of required dataset.please see and tell
me why it is not working with my dataset.
In abalone 9-18 dataset in 8th attribute '0'means negative instances and
'1' means positive instances. Please run this dataset with your technique
and let me know what wrong with this dataset.

**Comment by arjunpuri7** [comment]
i send file of dataset on your gmail address.

**Comment by gykovacs** [comment]
Hi arjunpuri7,

you might have misunderstood my previous comment. What I meant is that smote_variants is *NOT* intended to work with pandas data frames. Please convert your data to numpy arrays and it will work.
